---
- name: Install  Git and Clone Repository
  hosts: localhost
  become: yes  # This ensures the tasks run with sudo privileges
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone the public GitHub repository
      git:
        repo: 'https://github.com/Semantics-of-Sustainability/tempo-embeddings.git'
        dest: /scratch
        update: yes
    - name: Print completion message
      debug:
        msg: "Repository cloned and Python package installed successfully."


