# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = tempo_embeddings
SOURCEDIR     = .
BUILDDIR      = _build

# Set protobuf implementation to avoid this error: https://github.com/Semantics-of-Sustainability/tempo-embeddings/actions/runs/9450112946/job/26027944835?pr=54
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
