name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Set up Python
      - uses: chartboost/ruff-action@v1
        name: Check for linting errors
      - uses: chartboost/ruff-action@v1
        name: Check for import organization errors
        with:
          args: check --select I
